### PR TITLE
[Gear] Return functionality of cruciform_veinripper_proc_rate

### PR DESCRIPTION
**Pull request by JeremyMonk**
Tanks have been using this option to mean "time spent behind boss," and not literally changing the Proc rate. This is how the variable used to work prior to the latest commit.

This returns the functionality of that variable to the state that the tank Discords are using it and makes it clearer. Perhaps the variable name should be changed as well?

### CODE REVIEW

**Review by emallson — APPROVED** [review]
this looks fine to me. restores old functionality of the option. technically the option should probably get renamed but I can also just update the wiki to explain exactly what it is for. that avoids the class discords having to update pins etc. especially for an item that is going away soon:tm:

**Comment by EvanMichaels** [comment]
> this looks fine to me. restores old functionality of the option. technically the option should probably get renamed but I can also just update the wiki to explain exactly what it is for. that avoids the class discords having to update pins etc. especially for an item that is going away soon™️

I already checked in a version of this with a newly renamed option, see: https://github.com/simulationcraft/simc/commit/84a43a1349b18a9bb551bf89975a33740614a101

**Comment by emallson** [comment]
I was just about to comment on that 👍

**Comment by JeremyMonk** [comment]
I meant to close this following Koji's last commit

**Pull request closed without merging**
