### PR TITLE
[Priest] Update discipline APL

### PR DESCRIPTION
**Pull request by taherbert**

### CODE REVIEW

**Comment by seanpeters86** [comment]
Can you link a raidbots/url and/or the compiled APL to make it easier to review?

**Comment by taherbert** [comment]
Pastebin: https://pastebin.com/VcSHRWCp (updated 4/10)

**Comment by taherbert** [comment]
WIP update -- I need to revise the priority order for spells slightly to account for modifiers I missed on the discipline priest core passive, for example:

CleanShot 2023-04-08 at 10 13 22@2x

Won't modify the core structure of the APL, but will change timing variables pretty significantly.

**Comment by taherbert** [comment]
Pretty significant update, re-orders the priority of most spells inside of scov based on spell data modifications. Looking good now.

**Review by seanpeters86 — APPROVED** [review]

**Pull request merged**
