### PR TITLE
[Hunter] BM APL improvement pt.2

### PR DESCRIPTION
**Pull request by Ghosteld**
Second part of the changes;
- More liberal Bestial Wrath usage due to better gear, corruption bow effect, more stats, etc..

### CODE REVIEW

**Comment by Pewtro** [comment]
DPS loss using nonmeta talents, tested two fast:
Without TOTH: https://www.raidbots.com/simbot/report/vqWDfGAvVZd4puh21duDFd
Without OWTP: https://www.raidbots.com/simbot/report/kxjp2FidywKNCY93hwurar

**Comment by Ghosteld** [comment]
Nonmeta talents (like crows or chimaera shot) are not used and should not be used since the dps difference is too big to ever warrant picking them. https://www.raidbots.com/simbot/report/nZizoK7oWh3WuddNqdBNj6
Mythic Ny'alotha logs:  https://www.warcraftlogs.com/zone/statistics/24#class=Hunter&spec=BeastMastery&combatantinfo=Talents
One with the Pack used by 99.63% of hunters and Thrill of the Hunt used by 99,23% of the hunters

**Comment by Pewtro** [comment]
I am opposed to merging something that directly harms other talent choices, regardless of them being meta or not.

**Comment by Yuuseki** [comment]
may I propose changing the Bestial Wrath line instead?

current:
`actions.st+=/bestial_wrath,if=!buff.bestial_wrath.up&cooldown.aspect_of_the_wild.remains>15|target.time_to_die<15+gcd`

Ghost's suggestion:
`actions.st+=/bestial_wrath,if=buff.bestial_wrath.remains<gcd`

new suggestion:
`actions.st+="/bestial_wrath,if=talent.one_with_the_pack.enabled&talent.thrill_of_the_hunt.enabled&buff.bestial_wrath.remains<gcd|buff.bestial_wrath.down&cooldown.aspect_of_the_wild.remains>15|target.time_to_die<15+gcd"`


This change resolves the DPS loss from the two test cases provided by Putro:
Without TOTH: https://www.raidbots.com/simbot/report/wXmHSA9q1RihSWHTu1rVqo
Without OWTP: https://www.raidbots.com/simbot/report/dtwEtgtNsNi8npQ32B8qcn

**Pull request merged**
