### PR TITLE
Shaman Elemental APL

### PR DESCRIPTION
**Pull request by DenamPavel**
Fixed up the prepull and added a line to make EoGS use MotE better in the 1-2 target rotation, NEEDS A TEST RUN to make sure nothing broke

### CODE REVIEW

**Comment by scamille** [comment]
Are you using tabs instead of whitespace for indentation? Please use 2 white spaces per indentation level, see https://github.com/simulationcraft/simc/wiki/CodingGuidelines

**Comment by DenamPavel** [comment]
> 
> 
> Are you using tabs instead of whitespace for indentation? Please use 2 white spaces per indentation level, see https://github.com/simulationcraft/simc/wiki/CodingGuidelines

Wow that's embarrassing on my part, fixed that up

**Comment by Bloodmallet** [comment]
Hey @DenamPavel , thank you for the PR.
What exactly are you trying to fix during precombat?

**Comment by DenamPavel** [comment]
> 
> 
> Hey @DenamPavel , thank you for the PR.
> What exactly are you trying to fix during precombat?

I moved the prepull stuff into each rotation, as before 8739-8747 were applied across all 3 rotation types (STANDARD/SIMPLE/NEW), which ran into some problems with the NEW rotation. I did not want to change the actual STANDARD rotation as it currently exists, so I moved the prepull lines entirely within the IF statements to preserve that

**Pull request merged**
