### PR TITLE
[Warrior] Nominal DPS increase with 5 targets

### PR DESCRIPTION
**Pull request by CoilDomain**
Having WW at >1 above Rampage yielded 100-120 more DPS in 5 boss fights via Raidbots.

### CODE REVIEW

**Comment by Melekus** [comment]
Changing the default profiles only will not affect the APL used in most simulations, and will be overwritten whenever the default profiles are regenerated.
You should apply the changes here instead: https://github.com/simulationcraft/simc/blob/bfa-dev/engine/class_modules/sc_warrior.cpp#L4996

Your changes to the T23 default profile completely removed gear, talents, and other character information so it is no longer valid.

It is also usually recommended to link a reports showing the difference between the current APL and your proposed changes.

**Comment by CoilDomain** [comment]
Thanks, totally new to this. I assume there may be more than editing this section to place whirlwind above Rampage? I'm only familiar with the APL profile. If it's just that I'll run 10 sims of each to provide data.

`  default_list->add_talent( this, "Furious Slash",
                            "if=talent.furious_slash.enabled&(buff.furious_slash.stack<3|buff.furious_slash.remains<3|("
                            "cooldown.recklessness.remains<3&buff.furious_slash.remains<9))" );

  default_list->add_action( this, "Bloodthirst",
                            "if=equipped.kazzalax_fujiedas_fury&(buff.fujiedas_fury.down|remains<2)" );

  default_list->add_action( this, "Rampage", "if=cooldown.recklessness.remains<3" );

  default_list->add_action( this, "Recklessness" );

  default_list->add_action( this, "Whirlwind", "if=spell_targets.whirlwind>1&!buff.meat_cleaver.up" );
`

**Comment by Melekus** [comment]
Yeah that is enough. The actual profiles are created from that file whenever someone runs the regenerate script.

**Comment by CoilDomain** [comment]
Just updated that file, let me know if anythings off. Here are the sims

Current APL -- 5 Bosses(max targets for WW) at 5 minutes:
https://www.raidbots.com/simbot/report/hH6qqfktsTRdJqMMHcn4gJ
https://www.raidbots.com/simbot/report/jww61jJ7Si9UPWzTHbDcMn
https://www.raidbots.com/simbot/report/2vMVje1kBYK2kaPQebhBrW
https://www.raidbots.com/simbot/report/8N6gG9WxdwS3oiMhs35sa7
https://www.raidbots.com/simbot/report/tP21DdBAwSbkNrYWjNk6r2

Proposed APL -- 5 Bosses(max targets for WW) at 5 minutes:
https://www.raidbots.com/simbot/report/8qK21jGS5XXFBzavH6Nn1S
https://www.raidbots.com/simbot/report/7Vo7aiXTfJDiz1BGqcDrx4
https://www.raidbots.com/simbot/report/3Hujw95oKaQFCWmUv1ukdK
https://www.raidbots.com/simbot/report/5huw8UseX3KqD8VNzbh9vu
https://www.raidbots.com/simbot/report/kAdxAHqxZqkc3o1xi1FEeX

**Comment by Jundarer** [comment]
Change is already in the apl

**Pull request closed without merging**
