### PR TITLE
Updated for accurate max damage sim

### PR DESCRIPTION
**Pull request by squee666**
Gear summary needs fixed

### CODE REVIEW

**Comment by vituscze** [comment]
The file you edited is automatically generated, you need to edit this file instead: https://github.com/simulationcraft/simc/blob/bfa-dev/profiles/generators/Tier23/T23_Generate_Death_Knight.simc

**Comment by squee666** [comment]
> The file you edited is automatically generated, you need to edit this file instead: https://github.com/simulationcraft/simc/blob/bfa-dev/profiles/generators/Tier23/T23_Generate_Death_Knight.simc

thanks updated, though food profile and such wil need to be updated somehow

**Comment by vituscze** [comment]
Oh, and consumables need to be changed in the module.

**Comment by squee666** [comment]
nice timing lol

what about dungeon splice can i make it it use dfferent gear?

edit wheres module

**Pull request closed without merging**
