### PR TITLE
Checking what broke during the refactor, to prepare updating the refactor branch

### PR DESCRIPTION
**Pull request by Bloodmallet**

### CODE REVIEW

**Comment by Bloodmallet** [comment]
Looks like only Ember Elemental and Spark Elemental somehow create merge conflicts.

**Comment by scamille** [comment]
Is it possible for you to rebase the shaman changes on top of shadowlands instead of merging it, or does that cause too much trouble?

**Comment by Bloodmallet** [comment]
For me this was just a way to see what might need changes. Your question needs the attention of @Rusah

**Comment by scamille** [comment]
If shadowlands-shaman is to be considered a public branch where more than one people are working on, and you do not want to alter the history anyway, then merging is just fine.

I thought of it as more of a private branch, where rebasing might be an option and would give a cleaner change history when it eventually gets merged back to shadowlands. Both options have their pro and cons.

**Pull request closed without merging**
