### PR TITLE
[Monk] Add Brewmaster profiles

### PR DESCRIPTION
**Pull request by justindriggers**

### CODE REVIEW

**Comment by renanthera** [comment]
I have seen this PR, and it is on my to-do list to verify and merge.

**Comment by renanthera** [comment]
Finally had some time to look at it, looks like this profile is a fair bit behind our Credger.

I'll see what I can do about getting Credger to be a proper profile and merged, hopefully tonight.

**Comment by justindriggers** [comment]
> Finally had some time to look at it, looks like this profile is a fair bit behind our Credger.

Talents are based on my own usage, not necessarily optimal. Gear was selected from the Wowhead BiS list. Any changes are welcome though. Let me know if you'd like me to adjust anything.

**Comment by renanthera** [comment]
OK, I threw in what I have on hand for Credger.

It needs to be converted into a compliant profile, a double check to make sure no low-hanging fruit exist for optimizations, and I'd prefer the DW option gets dropped (as it's not an "interesting" variation).

You can tackle those if you want, although I'll double check it anyway, or I'll get to them tonight hopefully.

**Comment by justindriggers** [comment]
Made the Credger profile simc compliant, and removed the DW variant.

Can you fill me in on what Credger is?

**Comment by renanthera** [comment]
Whomever makes the base actor we end out passing around internally often has a blizzard randomly generated name for their character.

This cycle we have Credger courtesy of Sinzhu.

**Pull request merged**
