### PR TITLE
[Hunter] Update Hunter APL with Temporary Weapon Enchants

### PR DESCRIPTION
**Pull request by howlsome**
Hello!

I've added in the following temporary weapon enchants (at level 70 and 60) for:

- Beastmastery
- Markmanship
- Survival (renamed the strings for clarity)

Please be gentle, this is my first simc PR and I'm keen to learn to contribute to this more in the future.

### CODE REVIEW

**Comment by Pewtro** [comment]
The temporary enchants are already supported for all three specs, what is this intended to do?

**Comment by howlsome** [comment]
> The temporary enchants are already supported for all three specs, what is this intended to do?

Mind showing me where it's supported. When I was looking through the APL and so on, I found that only survival was listed in this file hence I thought maybe put it in then.

**Comment by Pewtro** [comment]
The two strings you are replacing are ternaries that change depending on if they're Survival or not, and that adds the necessary support since that means MM/BM will use Completely Safe Rockets and Survival will use Whetstone

**Comment by howlsome** [comment]
Hmm. Okay, I guess this is not needed then.

Do you think a comment line for clarity would help there for future purpose?

**Comment by Pewtro** [comment]
Not really, ternaries are pretty rudimentary syntax, and it's easily confirmable by running a sim as either BM, MM or SV that the enchants are working.

**Pull request closed without merging**
