### PR TITLE
[Priest] Add Devouring Plague

### PR DESCRIPTION
**Pull request by seanpeters86**

### CODE REVIEW

**Comment by seanpeters86** [comment]
@scamille @lgkern any idea why this isn't casting devouring plague? It adds the action just fine but the sim never seems to be able to use it

**Comment by scamille** [comment]
I found out how to fix the insanity overdrain warnings/crashes. But it is still not really casting it. I'll look further.

**Comment by scamille** [comment]
Please try again with my fixes.

**Comment by seanpeters86** [comment]
@scamille just pulled and merged with master still seeing the same results:

```
0.000 player 'Base' actions.default=mind_flay/devouring_plague
0.000 Player Base creates action devouring_plague (335467)
0.000 player 'Base' action 'devouring_plague' is affected by effect 179717 (Shadow Priest (id=137033) - effect #1)
0.000 action 'devouring_plague' base_dd_multiplier modified by -32.0%
0.000 player 'Base' action 'devouring_plague' is affected by effect 191068 (Shadow Priest (id=137033) - effect #2)
0.000 action 'devouring_plague' base_td_multiplier modified by -32.0%
0.000 player 'Base' action 'devouring_plague' (335467) affected by Voidform (idx=1).
0.000 player 'Base' action 'devouring_plague' (335467) affected by Voidform (idx=2).
0.000 player 'Base' action 'devouring_plague' (335467) affected by Shadowform (idx=1).
0.000 player 'Base' action 'devouring_plague' (335467) affected by Shadowform (idx=4).
0.000 player 'Base' action 'devouring_plague' (335467) affected by Twist of Fate (idx=1).
0.000 player 'Base' action 'devouring_plague' (335467) affected by Twist of Fate (idx=2).
0.000 player 'Base' action 'devouring_plague' (335467) affected by Mastery: Madness (idx=1).
0.000 player 'Base' action 'devouring_plague' (335467) affected by Mastery: Madness (idx=2).
...
300.000 action devouring_plague of Base is canceled
```

Profile:

```
debug=1

priest="Base"
level=60
role=spell
position=back
talents=1111111
spec=shadow

default_actions=0

actions=mind_flay
actions+=/devouring_plague

head=cowl_of_unspeakable_horrors,id=174116,ilevel=135
neck=heart_of_azeroth,id=158075,bonus_id=4929/5814/4936/1600
shoulder=spaulders_of_miasmic_mycelia,id=174117,ilevel=135
back=ashjrakamas_shroud_of_resolve,id=169223,bonus_id=6286
chest=robe_of_the_fallen_keeper,id=174115,ilevel=135
wrists=voiddrenched_wristwraps,id=174122,ilevel=130
hands=emberscale_gloves,id=174125,ilevel=130
waist=manainfused_sash,id=174124,ilevel=130
legs=trousers_of_peculiar_potency,id=174121,ilevel=130
feet=psychics_subtle_slippers,id=174123,ilevel=130
finger1=ring_of_collective_consciousness,id=174530,ilevel=130,enchant=accord_of_haste
finger2=ring_of_cosmic_potential,id=174533,ilevel=140,enchant=accord_of_haste
main_hand=vorzz_yoqal,id=172196,ilevel=130,enchant=quick_navigation
off_hand=uhnish_vwah,id=172190,ilevel=130

optimal_raid=0
override.bloodlust=0

```

**Comment by scamille** [comment]
I did not add it to the default APL. So you need to either do that or add it to your profiles APL.

It did work for me when I put it just before void eruption.

**Comment by seanpeters86** [comment]
Yeah it's in the apl of the profile I shared in the previous comment. Let me try cleaning out my build files and do a fresh build and see if that does it. Also I wonder if it only works to cast in voidform?

Edit: oof. Just realized the apl i was using above will never stop casting mind flay. That's for sure my problem

**Comment by seanpeters86** [comment]
Thanks for all your help @scamille !!

**Pull request merged**
