### PR TITLE
Fixed sim profile for t23 blood

### PR DESCRIPTION
**Pull request by squee666**

### CODE REVIEW

**Comment by Melekus** [comment]
Could you provide a raidbots/simc report comparing the current profile and your proposed improvements?

**Comment by squee666** [comment]
raid  before and after
https://www.raidbots.com/simbot/report/vjdURJa4mo4gCTHzyKZWJ6

**Review by squee666 — COMMENTED** [review]
https://www.raidbots.com/simbot/report/eALQsGsraWfNDS9ouZQLHx

round 2

**Review by squee666 — COMMENTED** [review]
F

**Comment by Melekus** [comment]
The simulation you linked here is for DungeonSlice, and changing talents to use Bonestorm (which isn't in the PR)
I assume that you would want to compare gear setups on Patchwerk (or maybe HecticAddCleave) rather than on DungeonSlice when specific profiles for that fight style already exist

**Comment by Melekus** [comment]
The author is inactive, i'll close the pull request and see if there's anything to salvage from the changes

**Pull request closed without merging**
