### PR TITLE
cmake improvements (integrate into synchronize.py)

### PR DESCRIPTION
**Pull request by athei**
Like discussed in #4341 I made some improvements to the cmake build system and integrated it into the `synchronize.py` architecture. This pull request only touches cmake files and the python thing.

This is the preparation pull request for the one that adds an option to cmake to disable threading.

The normal build file still builds. This is no wonder as I did not touched any files of them. However, the qmake build does not build for me:
`make: *** No rule to make target profiles/Tier22, needed by SimulationCraft.app/Contents/Resources/profiles/Tier22.  Stop.`

But this is also the case for `bfa-dev` and was not broken by my changes.

### CODE REVIEW

**Comment by scamille** [comment]
Looks good. I haven't tested it, but that can be done after the merge ;)

**Comment by athei** [comment]
Glad to hear. We are waiting for nav to look into it? I am just asking because I have follow up patches in the pipeline :)

**Comment by scamille** [comment]
add_compile_options(-fcolor-diagnostics) does not work for me. (Ubuntu 18.04 on Windows, using G++8.1.0):

c++: error: unrecognized command line option ‘-fcolor-diagnostics’

**Comment by athei** [comment]
> c++: error: unrecognized command line option ‘-fcolor-diagnostics’

Ooops. Thought it was the same command line option for clang and gcc. Postet a fix.

**Pull request merged**
