### PR TITLE
[Shaman] Updates to Ele AoE APL on 3-4t.

### PR DESCRIPTION
**Pull request by MadBubble**
1) Flame shock spread with SoP for hybrid lighting builds using WLR. 
2) Dont buff nonEOGS EQ in lightning builds.
3) Bring IF prio up for lighting builds on 3-4t and for fire on 3t. 
4) Buff SK Chain Lightings with Mote. 

<details><summary>Sims</summary>
<p>

Lightning ST - BYQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoVSSLJUSSLRDRJQiEAAAAAgSAikgiog0SSapEoEJBgA 
4t 5 min
https://www.raidbots.com/simbot/report/4DwtRUoBf2i4qSq9rHCEYM 
4t 1 min
https://www.raidbots.com/simbot/report/5JfWWArjcufspdah3iGCKP 
3t 5 min
https://www.raidbots.com/simbot/report/dgd1aqJTXj5sTYpyD18YZP 
3t 1 min
https://www.raidbots.com/simbot/report/n33dizUdvHvvvzgGguMwXG

Lightning st with EOGS - BYQAu3fz4tp2ZikXIAdNeR+oLAAAAAAAoVSSJJSRSLRDRJQiEAAAAAgSAJSCaiCSLJplSCAhEI 
4t 5 min
https://www.raidbots.com/simbot/report/bwRD346vXNeT4bL3QTrnbt 
4t 1 min
https://www.raidbots.com/simbot/report/v1GueoS4vXX1XiPFChnrZb 
3t 5 min
https://www.raidbots.com/simbot/report/mS2eKotSVe9CcPnBVkwpJU 
3t 1 min
https://www.raidbots.com/simbot/report/9FH1N8cmSNp3rVbkWVRLyW

Lightning m+ with PE - BYQAu3fz4tp2ZikXIAdNeR+oLAAAAAAAoVSSJJJlDk0S0QQBJSAAAAAAKBkUSCpIKi0SSaBQCBBC 
4t 5 min
https://www.raidbots.com/simbot/report/3y6YJLLbL9FmjUDC81b4EL 
4t 1 min
https://www.raidbots.com/simbot/report/qFLjtYEKZ3CvCH9DbP5BqP 
3t 5 min
https://www.raidbots.com/simbot/report/2jq5TadGxFBX4PkGqLbQoc 
3t 1 min
https://www.raidbots.com/simbot/report/tty6xdJwnSArQhUwHAbPhz

Lightning m+ with LMT - BYQAu3fz4tp2ZikXIAdNeR+oLAAAAAAAoVSSJJJlDk0S0QQDJSAAAAAAKBkIJkioISLJplSABBBC 
4t 5 min
https://www.raidbots.com/simbot/report/2WtMNKpZ6xXTsn1rZyxDp4 
4t 1 min
https://www.raidbots.com/simbot/report/n4FRnsondALb78pkcyB8UU 
3t 5 min
https://www.raidbots.com/simbot/report/phDbjSx7Kp3grinpfRm1ME 
3t 1 min
https://www.raidbots.com/simbot/report/3KsmRbbbnmQCeTMx212k9n

Wildfire with EB - BYQAAAAAAAAAAAAAAAAAAAAAAAAAAAAg0SrIJlkAJINKRLtkQOAAAAAAgSASJJkiog0SSaKBkQSAC 
4t 5 min
https://www.raidbots.com/simbot/report/pvsUrFNCPkc4devgtykXZj 
4t 1 min
https://www.raidbots.com/simbot/report/pomka5TxnYic5eyA1qCLCc 
3t 5 min
https://www.raidbots.com/simbot/report/fjZkxJoeRmuSaxYnnKnk7a 
3t 1 min
https://www.raidbots.com/simbot/report/iA49NGKVmix7N8jARwJJpe

Icyhot - BYQAAAAAAAAAAAAAAAAAAAAAAAAAAAAg0SrIJlkAJtINKRLNJEAAAAAAKBIlkQKiCSLJppEQCJBI 
4t 5 min
https://www.raidbots.com/simbot/report/oNaaNGR9aSv9EmDyN4r8sA 
4t 1 min
https://www.raidbots.com/simbot/report/929hgG7zK6LbanVdJhMbWN 
3t 5 min
https://www.raidbots.com/simbot/report/eQHf9mjCAXPDk2Uz6BWqoN 
3t 1 min
https://www.raidbots.com/simbot/report/m754GfdnYrvdzs34bnKgdD

Lightning without EB and with EOGS - BYQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoVSSLJJFSLRDRJQiEAAAAAgSAikgiog0SSapEoEJBgA 
4t 5 min
https://www.raidbots.com/simbot/report/d3F9yc9QGMqLg8JW4etU9z 
4t 1.5 min (shorter sims here make FoL screw up getting SK back) https://www.raidbots.com/simbot/report/oLw8E8m4bCyZLoXptwSh8u 
3t 5 min
https://www.raidbots.com/simbot/report/7bQw7JPRaHw4XMzLJJrLFr 
3t 1.5 min
https://www.raidbots.com/simbot/report/vLpW6FcBcTB9YqbAy649A9

Standard Rasz hybrid - BYQAu3fz4tp2ZikXIAdNeR+oLAAAAAAgUSrIJtkEkg0oE0kkkDAAAAAAoEgUSiSaog0SSaHoEoEEBI 
4t 5 min
https://www.raidbots.com/simbot/report/3EnPjahUeYC5gQJZR3xcSn 
4t 1 min
https://www.raidbots.com/simbot/report/abqCBFhiVnXFP7nyCq2qyo 
3t 5 min
https://www.raidbots.com/simbot/report/jq7Gpsn5fPpuCChRU6G8BA 
3t 1 min
https://www.raidbots.com/simbot/report/kWf2rvq4c23DvmFLNacvcL

</p>
</details>

### CODE REVIEW

**Comment by MadBubble** [comment]
2t and 1t sims
2t shows updates to aoe, 1t shows the gain from FS change (my APl had an extra condition that didnt prove to be useful so the end result matches Lucenia's with the tweaks)
<details><summary>Sims</summary>
<p>

Lighting ST with EOGS
2t 5 min
https://www.raidbots.com/simbot/report/o38Fm2atrn68F335twFj6f
1t 5 min
https://www.raidbots.com/simbot/report/vY2HXtdkRBhCCW5nE9nGmx

Lightning ST
2t 5 min
https://www.raidbots.com/simbot/report/iusbf4z6WJh3wkJgdFrBF4
1t 5 min
https://www.raidbots.com/simbot/report/iCD8WMp2P8q2cvbo1SjZxB

Lightning ST noEB
2t 5 min
https://www.raidbots.com/simbot/report/pXDnQLnMiTMWEaECxVgAxF
1t 5 min
https://www.raidbots.com/simbot/report/dELxRroQBdArmzWyb1yGiN

Lightning m+ with PE
2t 5 min
https://www.raidbots.com/simbot/report/4Pguj2DAGhCTwtr8eviFJ2
1t 5 min
https://www.raidbots.com/simbot/report/sbVnUvTSPEQtT1dTc23qMX

Lightning m+ with LMT
2t 5 min
https://www.raidbots.com/simbot/report/uG6wwZEyu6oMEon8X1HqT8
1t 5 min
https://www.raidbots.com/simbot/report/48ajUp9fxsJTEHihGziL2V

Wildfire
2t 5 min
https://www.raidbots.com/simbot/report/xx8DT8AC3mCJcPhJdcD1dE
1t 5min
https://www.raidbots.com/simbot/report/hU29j4eDb5BeJfgXo1mJXB

Icyhot
2t 5 min
https://www.raidbots.com/simbot/report/hWq2Di9rNDAFQGm3TGA3hg
1t 5 min
https://www.raidbots.com/simbot/report/9sSym3xEMaJz2QqKcKb7Tc


</p>
</details>

**Comment by MadBubble** [comment]
Sims for ST and precasts

@Bloodmallet @HawkCorrigan review pls

<details><summary>Sims</summary>
<p>

Lightning st - BYQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoVSSJJUSSLRDRJQiEAAAAAgSCIkolmog0SSapEAREgA
t29 4p BL
https://www.raidbots.com/simbot/report/5B5WTmiPHE1VcYgUzaz9U6
t29 4p noBL
https://www.raidbots.com/simbot/report/oeYj5uTHUoKbV1qdf5Hk3G
2p/2p BL
https://www.raidbots.com/simbot/report/hHXpudZwAFUWaZNxExYDWg
2p/2p noBL
https://www.raidbots.com/simbot/report/6Qhaiq5cetYpSJCih4z6Lx
t30 4p BL
https://www.raidbots.com/simbot/report/bppVskBqxvAwUgQoz8JTQM
t30 4p noBL
https://www.raidbots.com/simbot/report/7FWQ8gEgkxEuWMDappReUD

Lightning st ES + FoL - BYQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoVSSJJRJSLRDRJQiEAAAAAgSCIkolmog0SSapEAREgA
t29 4p BL
https://www.raidbots.com/simbot/report/7uZBK7bxBYGCpfBofnA8XF
t29 4p noBL
https://www.raidbots.com/simbot/report/cdFnV7JEatFZneSJmFADkw
2p/2p BL
https://www.raidbots.com/simbot/report/srawdGVFapaMHRfj1L2VmR
2p/2p noBL
https://www.raidbots.com/simbot/report/mG63Q835vXPQvJFmW7FvYm
t30 4p BL
https://www.raidbots.com/simbot/report/tigZnZmWheFaxsURHRf6xq
t30 4p noBL
https://www.raidbots.com/simbot/report/8pmxgpDD33spAFGqUFHyvi

Lightning st ES + LMT - BYQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoVSSJJUi0S0QUSDJSAAAAAAKJgQiWaiCSLJplSAERAC
t29 4p BL
https://www.raidbots.com/simbot/report/pdyTYB4qCjnpnHTRCELAZj
t29 4p noBL
https://www.raidbots.com/simbot/report/iKdmiDzVvBvkr3T7LqVp7z
2p/2p BL
https://www.raidbots.com/simbot/report/cXnZgmQ82FWofSd1TZ22bb
2p/2p noBL
https://www.raidbots.com/simbot/report/jNcqHKLGY5maB76uA3PdUz
t30 4p BL
https://www.raidbots.com/simbot/report/6zvRDrjeg51XfRNdY39gfB
t30 4p noBL
https://www.raidbots.com/simbot/report/gG1LdhRrSDX4chisJjwpoc

Lightning m+ with PE - BYQAu3fz4tp2ZikXIAdNeR+oLAAAAAAAoVSSJJJlDk0S0QQBJSAAAAAAKBkUSCpIKi0SSaBQCBBC
t29 4p BL
https://www.raidbots.com/simbot/report/wPyw3Vcm4REXH8G3rwF62n
t29 4p noBL
https://www.raidbots.com/simbot/report/wYFp5PEEPoXg1esWk3uLW8
2p/2p BL
https://www.raidbots.com/simbot/report/rRn6uHng1RCv35deAZiS1H
2p/2p noBL
https://www.raidbots.com/simbot/report/q1PoiMWhzgSHT5XuuPxQFo
t30 4p BL
https://www.raidbots.com/simbot/report/9ctdzsTsZCBegSHFxRWXza
t30 4p noBL
https://www.raidbots.com/simbot/report/dFxFtxZgAgezQbYCuh558C

Lightning m+ with LMT - BYQAu3fz4tp2ZikXIAdNeR+oLAAAAAAAoVSSJJJlDk0S0QQDJSAAAAAAKBkIJkioISLJplSABBBC
t29 4p BL
https://www.raidbots.com/simbot/report/sp4JX47eiBTptoccysiueg
t29 4p noBL
https://www.raidbots.com/simbot/report/7Acoz4i9pLnKpGbfuXyS7N
2p/2p BL
https://www.raidbots.com/simbot/report/heYPSweDoDdZmU9VRz3VPR
2p/2p noBL
https://www.raidbots.com/simbot/report/the45XoUoXLQMebNAznfjD
t30 4p BL
https://www.raidbots.com/simbot/report/5onkfV4eby2N3HKa9NCfG5
t30 4p noBL
https://www.raidbots.com/simbot/report/vpQvfvD8vZvRzbMU48KH1s

WildFire - BYQAAAAAAAAAAAAAAAAAAAAAAAAAAAAg0SrIJlkAJINKRLtkQOAAAAAAgSASJJkiog0SSaKBkQSAC
t29 4p BL
https://www.raidbots.com/simbot/report/jW7YojcTHJaHKojsfT8enL
t29 4p noBL
https://www.raidbots.com/simbot/report/22izd7kQSHzWrNTpGbXU97
2p/2p BL
https://www.raidbots.com/simbot/report/jw5yvs3LJswdzJQamD2dnE
2p/2p noBL
https://www.raidbots.com/simbot/report/fpaWgznZuDYDwanvicTb1e
t30 4p BL
https://www.raidbots.com/simbot/report/pK8RyJrgzyeTU6E9HMixFn
t30 4p noBL
https://www.raidbots.com/simbot/report/dptdYYZQs8uPoLoBLS4Zbe

Icyhot - BYQAAAAAAAAAAAAAAAAAAAAAAAAAAAAg0SrIJlkAJtINKRLNJEAAAAAAKBIlkQKiCSLJppEQCJBI
t29 4p BL
https://www.raidbots.com/simbot/report/dPVsJUf2i56yxERi83SQnX
t29 4p noBL
https://www.raidbots.com/simbot/report/kcB6VXP2ncTgtChZAaSyAQ
2p/2p BL
https://www.raidbots.com/simbot/report/6nM355rV8gYmZATaXcW2mg
2p/2p noBL
https://www.raidbots.com/simbot/report/n1DqKqb4Juc6xYEpfwm6J3
t30 4p BL
https://www.raidbots.com/simbot/report/p8inekbcJjMt2YzVzEx7fi
t30 4p noBL
https://www.raidbots.com/simbot/report/buoSqa8oTNrvYzeZuBV1yd

Fire MWF ST - BYQAAAAAAAAAAAAAAAAAAAAAAAAAAAAgUSrUSCAJlkUoEOgkkEBAAAAAoEgUSCpIKItkkmSAJkEgA
t29 4p BL
https://www.raidbots.com/simbot/report/wGTXvJDdk7uQ4jS49QGbo5
t29 4p noBL
https://www.raidbots.com/simbot/report/dRLQbBcmZ9jBHs3ABx61r6
2p/2p BL
https://www.raidbots.com/simbot/report/b22wjijkVr4QTcanXAZv9n
2p/2p noBL
https://www.raidbots.com/simbot/report/nfaXpDcWKYNoQ8vsU42gqs
t30 4p BL
https://www.raidbots.com/simbot/report/6FH2img2QHwJcPYsRm8KKg
t30 4p noBL
https://www.raidbots.com/simbot/report/joZu9PdJsbenayr6njDGPE

Rasz 100 - BYQAAAAAAAAAAAAAAAAAAAAAAAAAAAAgUSrIJlkAJINKBtkkkDAAAAAAoEgUSCpIKItkkmSAJkEgA
t29 4p BL
https://www.raidbots.com/simbot/report/aSiJX3maoY6VqaWEEDNequ
t29 4p noBL
https://www.raidbots.com/simbot/report/5GxD8T9QpMgVmWYJVkmgrG
2p/2p BL
https://www.raidbots.com/simbot/report/iJbBv44TMx4zr7cjNsE3uD
2p/2p noBL
https://www.raidbots.com/simbot/report/ozK12dweojPowUnPFhdYtf
t30 4p BL
https://www.raidbots.com/simbot/report/3Q68mzWgoM4fmWJpzcDJeg
t30 4p noBL
https://www.raidbots.com/simbot/report/7VmmceEnMdRhmabP4LsMMF

Rasz 150 - BYQAAAAAAAAAAAAAAAAAAAAAAAAAAAAgUSrUSSJJQCJNKBNSSEAAAAAgSASJJkiog0SSaKBkQSAC
t29 4p BL
https://www.raidbots.com/simbot/report/1K2mbnmN5DTd8tu5xZwAFn
t29 4p noBL
https://www.raidbots.com/simbot/report/jnWcKCUSY45UHpVrwPoxxP
2p/2p BL
https://www.raidbots.com/simbot/report/biB1g8T4nTtoDiLg1Vob16
2p/2p noBL
https://www.raidbots.com/simbot/report/fHGgqLpZyixueYapDJpjbk
t30 4p BL
https://www.raidbots.com/simbot/report/f62kbDq4Ux67FdySRiNzLG
t30 4p noBL
https://www.raidbots.com/simbot/report/7KRMj3EHJ9sfbLJKVQ39WF

Rasz with IF - BYQAAAAAAAAAAAAAAAAAAAAAAAAAAAAgUSrIJtkAJtINKBIJJAAAAAAaBQJJgog0SSapEgQSAC
t29 4p BL
https://www.raidbots.com/simbot/report/oWSDReUUsyE3i9iz4KcXfU
t29 4p noBL
https://www.raidbots.com/simbot/report/3pAASWAyXx8Jtdwsvra7VK
2p/2p BL
https://www.raidbots.com/simbot/report/8hxhjTChzZXfHFwQQrF8x7
2p/2p noBL
https://www.raidbots.com/simbot/report/6WeEha3Mp4TS8MWjuMSJE3
t30 4p BL
https://www.raidbots.com/simbot/report/e39uKyG3iRicBBm92JfgPB
t30 4p noBL
https://www.raidbots.com/simbot/report/cCN9Bk3eoeZe6BqrPy6vej

</p>
</details>

**Comment by Bloodmallet** [comment]
@MadBubble after merging something else, this one got conflicts. Please double check them.

**Comment by Bloodmallet** [comment]
Created a new PR.

**Pull request closed without merging**
