### PR TITLE
[Warlock] Implemented Conduits and added dot to Malefic Rapture

### PR DESCRIPTION
**Pull request by mutasDev**
Added Conduits : Cold Embrace ( modifying Shadow Embrace damage ) and Focused Malignancy ( increases Malefic Rapture DMG on targets affected by Unstable Affliction)

Added Phantom Singularity to Malefic Rapture Damage Calculation.

### CODE REVIEW

**Comment by Azevara** [comment]
I believe the section for Focused Malignancy requires a check that the specific target has UA? On a related note, have you checked that these spells give the correct damage output in simc once you made these changes?

**Review by Azevara — CHANGES_REQUESTED** [review]
There's a few whitespace issues lingering that may be the result of tabs. Make sure only spaces are used and that lines are consistent with existing code.

Also, as discussed earlier, please run tests of the changes by running examples on a fresh build of simc and comparing with beta client where appropriate. Contact one of the team members listed on this issue to present and discuss those tests in order to have this merged.

**Review by nasirabtw — APPROVED** [review]
Best to just get your compiler to use the clang file for formatting purposes in Warlock.

**Review by nasirabtw — COMMENTED** [review]
Best to just use the clang file to format anything related for Warlock module.

**Comment by Azevara** [comment]
I'm going to go ahead and merge this in and include notes in our tracking spreadsheet about needing auditing prior to SL launch. It will remain "In Beta" until someone verifies simc vs client behavior.

**Pull request merged**
