### PR TITLE
Fix for mind blast with dark thought up ignoring its own cooldown.

### LINKED ISSUE #35: Remove implemenation of Dark Thoughts Bug once fixed in-game
In the future the `ready()` method in `mind_blast_t` will need to be `overriden` to allow the casting of mindblast while you do not have a full charge if you have a buff. Currently it's being bypassed by the fact that if you have the buff you always have a blast charge since getting a proc currently resets the charge.

### PR DESCRIPTION
**Pull request by scamille**
resolves https://github.com/WarcraftPriests/sl-shadow-priest/issues/35

### CODE REVIEW

**Comment by seanpeters86** [comment]
Using this profile to test:

```
priest="Publik"
level=60
race=pandaren
region=us
role=spell
talents=2121113
spec=shadow

flask=disabled
food=disabled

covenant=venthyr
soulbind=nadjia_the_mistblade,331576/107:1/85:1/331579/72:1/331584/115:1/331586

default_actions=0

actions=mind_blast
actions+=/void_eruption
actions+=/shadow_word_pain,if=refreshable
actions+=/mind_flay,chain=1,interrupt_immediate=1,interrupt_if=ticks>=2

head=,id=173245,bonus_id=6716/1487/6982/6649/6648
neck=,id=177165,bonus_id=6938,drop_level=50
shoulder=,id=163425,bonus_id=6938,drop_level=50
back=,id=183705
chest=,id=163429,bonus_id=6938,drop_level=50
wrist=,id=177098,bonus_id=6938,drop_level=50
hands=,id=180911,bonus_id=7195/1472/6616
waist=,id=163431,bonus_id=6938,drop_level=50
legs=,id=177096,bonus_id=6938,drop_level=50
feet=,id=177095,bonus_id=6938,drop_level=50
finger1=,id=177164,bonus_id=6938,drop_level=50
finger2=,id=177167,bonus_id=6938/1765,drop_level=50
main_hand=,id=184320,bonus_id=6706/7173,drop_level=60

single_actor_batch=1
optimal_raid=0
desired_targets=1
iterations=10000
```

Not seeing anything out of the ordinary, although casts look identical to `shadowlands` but that might just be coincidence, this "bug" only really shaves off a few seconds of blast so it can be difficult to see in the apl. 

## Before
before

## After
after

Idk if you want to do more testing/add any logging somewhere but on the surface this looks good to me.

CC: @Saeldur as well in case he wants to test himself

**Comment by Saeldur** [comment]
I went and tested this and it behaves exactly the same as my previous implementation in #5347 but will be more maintainable.
This PR can't be pulled exactly as it as it doesn't disable the [trigger override](https://github.com/simulationcraft/simc/blob/10e273d82106a079518aa9da3702422ba425f467/engine/class_modules/priest/sc_priest_shadow.cpp#L1840-L1848 ) for dark_thoughts_t.
With that change made though it will fix the issue perfectly.

**Review by Saeldur — CHANGES_REQUESTED** [review]
I went and tested this and it behaves exactly the same as my previous implementation in #5347 but will be more maintainable.
This PR can't be pulled exactly as it as it doesn't disable the trigger override for dark thoughts giving the extra mindblasts.
https://github.com/simulationcraft/simc/blob/10e273d82106a079518aa9da3702422ba425f467/engine/class_modules/priest/sc_priest_shadow.cpp#L1840-L1848 Needs to be removed for this to be complete.

**Comment by scamille** [comment]
Thanks for testing and reviewing it. I'll remove the trigger override tonight.

This solution is still not perfect - that would require some support in action_t core for either dynamically enabling/disabling cooldowns or dynamically selecting a cooldown (so this solution but just with less ugly code). But I don't think it is worth it for now.

**Review by seanpeters86 — APPROVED** [review]

**Pull request merged**
