### PR TITLE
[Shaman] Add support for Chains of Devastation legendary

### PR DESCRIPTION
**Pull request by zab-w**
Current version of simc doesn't recognize shaman APL records like:
```
actions.aoe+=/chain_lightning,if=buff.chains_of_devastation_chain_lightning.up
actions.aoe+=/chain_heal,if=buff.chains_of_devastation_chain_heal.up
```
Following changes were made to fix this:
1. Fix constructors for healing spells.
2. Add dmg buff for chain lightning.
3. Add cost buff for chain heal.
4. Fix spell ids for Chains of Devastation buffs. It were anima buff ids before. Also see questions.
5. Fix cast time effect for chain heal in spell db.

Questions
1. In spell db Chains of Devastation for chain heal has id 336735, but on wowhead it's runecarving power. Where is mistake? In game ids are equal to wowhead. Chain heal buff 336737; Chain lightning buff 336736.
2. I've patched sc_spell_data.inc and sc_spell_data_ptr.inc manually, but I'm not sure that it's OK. Could some one guide me on changes for this?

### CODE REVIEW

**Comment by scamille** [comment]
The spell data files are auto-generated and should definitely not be edited manually - they will just be overridden next time.

For runeforged legendaries you can use find_runeforge_legendary("Chains of Devastation") to get at the data, which would contain https://www.wowhead.com/spell=336735/chains-of-devastation

Spell query gives:
```

Name             : Chains of Devastation (id=336735) [Spell Family (11), Hidden]
School           : Physical
Spell Type       : None
Duration         : Aura (infinite)
Proc Chance      : 101%
Proc Flags       : ........ ..x.x.x. x....... ........
                 : Generic Heal, Generic Hostile Spell, Magic Heal, Magic Hostile Spell
Attributes       : .......x ........ ........ .......x   ........ ..x..... ........ ........
                 : ........ ........ ........ ....x...   ........ ........ xx..x... ..x.....
                 : ........ ........ .......x ........   ........ ........ ........ ........
                 : ........ ....x... ........ ........   ........ ........ ........ ........
                 : ........ ....x... ........ ........   ........ ........ ........ ........
                 : ........ ........ ........ ........   ........ ........ ........ ...x....
                 : ........ ........ ........ ........   ........ ........ ........ .x......
                 : ........ ........ ........ ........
                 : Hidden (7), Cannot cancel aura (31), Disable player procs (112), Disable target procs (113), Disable weapon procs (151)
Effects          :
#1 (id=834313)   : Apply Aura (6) | Dummy (4)
                   Base Value: 0 | Scaled Value: 0 | PvP Coefficient: 1.00000 | Target: Self (1)
Description      : Casting Chain Heal makes your next Chain Lightning instant cast$?$c1|c2[ and deal $336736s2% increased damage][]. Casting Chain Lightning makes your next Chain Heal instant cast$?$c1|c2[ and consume no mana][].
```
and
```
SimulationCraft 905-01 for World of Warcraft 9.0.5.37988 Live (hotfix 2021-03-23/37988, git build shadowlands 2ff222a)

Name             : Chains of Devastation (id=336736) [Spell Family (11)]
School           : Physical
Spell Type       : None
Duration         : 20 seconds
Stacks           : 1 initial, 1 maximum
Proc Chance      : 101%
Proc Flags       : ........ ....x... x....... ........
                 : Generic Hostile Spell, Magic Hostile Spell
Attributes       : ........ ........ ........ .......x   ........ ..x..... ........ ........
                 : ........ ........ ........ ....x...   ........ ........ xx..x... ........
                 : ........ ........ .......x ........   ........ ........ ........ ........
                 : ........ ....x... ........ ........   ........ ........ ........ ........
                 : ........ ....x... ........ ........   ........ ........ ........ ........
                 : ........ ........ ........ ........   ........ ........ ........ ...x....
                 : ........ ........ ........ ........   ........ ........ ........ .x......
                 : ........ ........ ........ ........
                 : Cannot cancel aura (31), Disable player procs (112), Disable target procs (113), Disable weapon procs (151)
Effects          :
#1 (id=834314)   : Apply Aura (6) | Add Percent Modifier (108): Spell Cast Time (10)
                   Base Value: -100 | Scaled Value: -100 | PvP Coefficient: 1.00000 | Misc Value: 10 | Target: Self (1)
                   Affected Spells: Lava Beam (114074), Chain Lightning (188443)
                   Family Flags: 1, 34
#2 (id=873589)   : Apply Aura (6) | Add Percent Modifier (108): Spell Direct Amount (0)
                   Base Value: 50 | Scaled Value: 50 | PvP Coefficient: 1.00000 | Target: Self (1)
                   Affected Spells: Lava Beam (114074), Chain Lightning (188443)
                   Family Flags: 1, 34
Description      : $@spelldesc336735
Tooltip          : Your next Chain Lightning will be instant cast$?$c1|c2[ and deal $s2% increased damage][].
```

There seems to be nothing in spell data directly pointing from 336735 to 336736 besides the tooltip, so you would just have to manually get at the 336736 spell data.

So eg. 
```
legendary.chains_of_devastation = find_runeforge_legendary("Chains of Devastation");
buffs.chains_of_devastation = make_buff( this, "chains_of_devastation_chain_lightning", find_spell( 336736 ) ).proc_chance(legendary.chains_of_devastation.ok()?1.0 : 0.0);
```

I am also not sure if you really need to check for the spec, or if having the legendary equipped should be enough to activate this effect?

**Comment by zab-w** [comment]
> There seems to be nothing in spell data directly pointing from 336735 to 336736 besides the tooltip, so you would just have to manually get at the 336736 spell data.

But what about Chain heal buff, spell id 336737? It looks like missing in spell data db.

**Comment by scamille** [comment]
That then needs whitelisting in the dbc export configuration. I'll try to add that later so you can do your work with the spell available.

**Comment by scamille** [comment]
Added in 5bf48edf23c121b25d908a73718e911e4af4d065 , just needs someone to regenerate spelldata.

**Comment by zab-w** [comment]
Is there anything left to do in this PR to make it merged?

**Comment by scamille** [comment]
Looks good to me.

**Pull request merged**
