### PR TITLE
added dummy profiles to get docker to work

### PR DESCRIPTION
**Pull request by JontiH**
As discussed here:

https://github.com/simulationcraft/simc/issues/6683

The empty profile doesn't work for building the docker image.

I created a folder of super basic dummy profiles for each spec in order to get the dockerfile to build properly.

Hopefully this will suffice until things are all ported and proper APLs are built, and furthermore the dummy APLs should be pretty agnostic across expansions, so they can be used in the time between other expansions

### CODE REVIEW

**Comment by jharris-tc** [comment]
@Horaddrim can you merge this?

**Review by Bloodmallet — CHANGES_REQUESTED** [review]
Please add Devastation Evoker, too.

I think empty profile could be useful for something. I'm undecided whether these should be generated as generator-profiles too. This way they would contain an APL.
Oh and while the goal of "these will work between expansions" is a good one, it won't be fulfilled because between expansions whole specs usually break in SimulationCraft because spelldata is shifted around so much.
Therefore this reason might not apply.

**Comment by jharris-tc** [comment]
> Please add Devastation Evoker, too.
> 
> I think empty profile could be useful for something. I'm undecided whether these should be generated as generator-profiles too. This way they would contain an APL. Oh and while the goal of "these will work between expansions" is a good one, it won't be fulfilled because between expansions whole specs usually break in SimulationCraft because spelldata is shifted around so much. Therefore this reason might not apply.

well the whole idea with these dummy profiles is that they that they literally don't do anything. 

so for example, look at the VDH dummy

demonhunter="T28_Demon_Hunter_Vengeance"
source=default
spec=vengeance
level=60
race=blood_elf
role=tank
position=front
actions=use_items
main_hand=drustlords_greataxe,id=178713,bonus_id=6807/1498/6646,enchant=sinful_revelation


All it does is uses items, and beyond having a weapon equipped (I just picked one), it doesn't have any gear. So even if spelldata is shifted around, this should theoretically still build.

if I'm being honest, maybe the better path longterm is to add the ability to turn profiling off when building the Dockerfile. The engine itself should still be able to build even if APLs aren't working, because I would still be able to make my own custom APL and run it. But for now I think this is a good stopgap to provide a docker image people can use to play around with.

Does that make sense @Bloodmallet

**Comment by JontiH** [comment]
> Please add Devastation Evoker, too.
> 
> I think empty profile could be useful for something. I'm undecided whether these should be generated as generator-profiles too. This way they would contain an APL. Oh and while the goal of "these will work between expansions" is a good one, it won't be fulfilled because between expansions whole specs usually break in SimulationCraft because spelldata is shifted around so much. Therefore this reason might not apply.

> Please add Devastation Evoker, too.
> 
> I think empty profile could be useful for something. I'm undecided whether these should be generated as generator-profiles too. This way they would contain an APL. Oh and while the goal of "these will work between expansions" is a good one, it won't be fulfilled because between expansions whole specs usually break in SimulationCraft because spelldata is shifted around so much. Therefore this reason might not apply.

well the whole idea with these dummy profiles is that they that they literally don't do anything. 

so for example, look at the VDH dummy

```
demonhunter="T28_Demon_Hunter_Vengeance"
source=default
spec=vengeance
level=60
race=blood_elf
role=tank
position=front
actions=use_items
main_hand=drustlords_greataxe,id=178713,bonus_id=6807/1498/6646,enchant=sinful_revelation
```

All it does is uses items, and beyond having a weapon equipped (I just picked one), it doesn't have any gear. So even if spelldata is shifted around, this should build. I have built it myself, and run a sim with a custom (shitty) apl for a hunter.

if I'm being honest, maybe the better path longterm is to add the ability to turn profiling off when building the Dockerfile. The engine itself should still be able to build even if APLs aren't working, because I would still be able to make my own custom APL and run it. But for now I think this is a good stopgap to provide a docker image people can use to play around with.

Does that make sense @Bloodmallet

**Pull request closed without merging**
